// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6WKn6Caa0PzfIaVwSoWcYvmqKT3o_mT8',
    appId: '1:1061770705284:web:497ca6a97fc975b82b85d1',
    messagingSenderId: '1061770705284',
    projectId: 'government-86a70',
    authDomain: 'government-86a70.firebaseapp.com',
    storageBucket: 'government-86a70.appspot.com',
    measurementId: 'G-TL0X8VFV7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4kgWUcIxB-PSSGcTCVD0E_6nJ5b8_-vc',
    appId: '1:327589863812:android:76486b55e7d75d5da17dd1',
    messagingSenderId: '327589863812',
    projectId: 'govscheme-a548b',
    storageBucket: 'govscheme-a548b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPnGBalET8VUXPyW3jXl_A2QnVtRbu300',
    appId: '1:327589863812:ios:6ec9347912d7b142a17dd1',
    messagingSenderId: '327589863812',
    projectId: 'govscheme-a548b',
    storageBucket: 'govscheme-a548b.appspot.com',
    iosBundleId: 'com.example.governmentSchemeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNNDcVNF53U9AfDcbX_ys7jO_phWeZnPQ',
    appId: '1:1061770705284:ios:8fc47c6e1a28a8462b85d1',
    messagingSenderId: '1061770705284',
    projectId: 'government-86a70',
    storageBucket: 'government-86a70.appspot.com',
    iosBundleId: 'com.example.governmentSchemeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6WKn6Caa0PzfIaVwSoWcYvmqKT3o_mT8',
    appId: '1:1061770705284:web:1fb04667fa6334462b85d1',
    messagingSenderId: '1061770705284',
    projectId: 'government-86a70',
    authDomain: 'government-86a70.firebaseapp.com',
    storageBucket: 'government-86a70.appspot.com',
    measurementId: 'G-FJ6NL58F5D',
  );

}